### ISSUE TITLE
[FEAT] 채팅뷰 UI 구성하기

### ISSUE THREAD

**Issue by hwangJi-dev** [SOPT-29th-JointSeminar-9/Client-iOS#1]
## 📌  Feature Issue
채팅뷰 UI 구성하기

## 📝  To-do
- [x] 뮤직허그 topNaviBar - ReusableView 생성
- [x] headerCell (텍스트만 존재하는) 생성
- [x] musicPlayChatCell 생성 (음악 재생됩니다 Cell)
- [x] counterPartChatCell 생성
- [x] myChatCell 생성
- [ ] Message 상태 구분하여 셀 등록 (musicPlay / counterPartChat / myChat)
- [ ] bottom texting Area -  ReusableView 생성
- [ ] textingAreaView와 chattingMusicBar UI Layout 구성 
- [ ] 커스텀 Cell과 데이터 CollectionView에 연결하여 채팅 UI 구성
