### ISSUE TITLE
[FEAT] 맨위로 버튼 구현

### ISSUE THREAD

**Issue by jumining** [SOPT-29th-JointSeminar-9/Client-iOS#18]
## 📌  Feature Issue

'맨위로' 버튼을 구현합니다.
<img width="366" alt="image" src="https://user-images.githubusercontent.com/76610340/143443103-90d87b19-2585-4065-864a-5ef76c3204a9.png">

## 📝  To-do

- [x] 버튼 xib파일 만들기
- [x] 버튼 UI구성하고 셀에 넣기
- [x] 맨 밑에 추가 공간의 뷰를 만들어서 테이블뷰에 넣기(하단 뮤직재생바가 셀을 가리는 문제 해결)
